/* Copyright (c) 2020 . All Rights Reserved. */

import { Injectable } from '@angular/core';
import { Http, Response, URLSearchParams, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { Headers } from '@angular/http';
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/map';
import { PremiumMaster} from "../../api-models"

var premiumMaster1 = new PremiumMaster();
premiumMaster1.excludeCapClmDtl ="sample data1";
premiumMaster1.dentalCobCalcMethod ="sample data1";
premiumMaster1.claimFilingIndicator ="sample data1";
premiumMaster1.rateModifyDate =new Date('2010-01-01');
premiumMaster1.cobExcludeCapClaimCode ="sample data1";
premiumMaster1.cobPolicyFlag ="sample data1";
premiumMaster1.depDetermRuleCode ="sample data1";
premiumMaster1.instCobCalcMethod ="sample data1";
premiumMaster1.rateCategory ="sample data1";
premiumMaster1.commissionGlRefCode ="sample data1";
premiumMaster1.commissionCompanyCode ="sample data1";
premiumMaster1.commissionMatrixDef ="sample data1";
premiumMaster1.cobCalcMethod ="sample data1";
premiumMaster1.reasonCode ="sample data1";
premiumMaster1.applyPcp ="sample data1";
premiumMaster1.exclusionPeriod =123;
premiumMaster1.exclusionType ="sample data1";
premiumMaster1.adFeeLevelCode ="sample data1";
premiumMaster1.updateProcess ="sample data1";
premiumMaster1.updateUser ="sample data1";
premiumMaster1.updateDatetime =new Date('2010-01-01');
premiumMaster1.insertProcess ="sample data1";
premiumMaster1.insertUser ="sample data1";
premiumMaster1.insertDatetime =new Date('2010-01-01');
premiumMaster1.securityCode ="sample data1";
premiumMaster1.geographicRegion ="sample data1";
premiumMaster1.specPgmProcessCd ="sample data1";
premiumMaster1.adFeeGlCode ="sample data1";
premiumMaster1.adFeeCompCode ="sample data1";
premiumMaster1.adminFee =123;
premiumMaster1.pctOfMatrix =123;
premiumMaster1.matrixDef ="sample data1";
premiumMaster1.pctAllowed =123;
premiumMaster1.priceOrAdjudicate ="sample data1";
premiumMaster1.pctOfBilled =123;
premiumMaster1.priceSchedule2 ="sample data1";
premiumMaster1.priceSchedule1 ="sample data1";
premiumMaster1.priceRule2 ="sample data1";
premiumMaster1.priceRule1 ="sample data1";
premiumMaster1.rate5 =123;
premiumMaster1.rate4 =123;
premiumMaster1.rate3 =123;
premiumMaster1.rate2 =123;
premiumMaster1.rate1 =123;
premiumMaster1.tieringMethod ="sample data1";
premiumMaster1.glRefCode ="sample data1";
premiumMaster1.companyCode ="sample data1";
premiumMaster1.lineOfBusiness ="sample data1";
premiumMaster1.benefitPackageId ="sample data1";
premiumMaster1.endDate =new Date('2010-01-01');
premiumMaster1.effectiveDate =new Date('2010-01-01');
premiumMaster1.planRiderCode ="sample data1";
premiumMaster1.recordType ="sample data1";
premiumMaster1.seqGroupId =123;
premiumMaster1.seqPremId =123;

var premiumMaster2 = new PremiumMaster();
premiumMaster2.excludeCapClmDtl ="sample data2";
premiumMaster2.dentalCobCalcMethod ="sample data2";
premiumMaster2.claimFilingIndicator ="sample data2";
premiumMaster2.rateModifyDate =new Date('2010-01-01');
premiumMaster2.cobExcludeCapClaimCode ="sample data2";
premiumMaster2.cobPolicyFlag ="sample data2";
premiumMaster2.depDetermRuleCode ="sample data2";
premiumMaster2.instCobCalcMethod ="sample data2";
premiumMaster2.rateCategory ="sample data2";
premiumMaster2.commissionGlRefCode ="sample data2";
premiumMaster2.commissionCompanyCode ="sample data2";
premiumMaster2.commissionMatrixDef ="sample data2";
premiumMaster2.cobCalcMethod ="sample data2";
premiumMaster2.reasonCode ="sample data2";
premiumMaster2.applyPcp ="sample data2";
premiumMaster2.exclusionPeriod =123;
premiumMaster2.exclusionType ="sample data2";
premiumMaster2.adFeeLevelCode ="sample data2";
premiumMaster2.updateProcess ="sample data2";
premiumMaster2.updateUser ="sample data2";
premiumMaster2.updateDatetime =new Date('2010-01-01');
premiumMaster2.insertProcess ="sample data2";
premiumMaster2.insertUser ="sample data2";
premiumMaster2.insertDatetime =new Date('2010-01-01');
premiumMaster2.securityCode ="sample data2";
premiumMaster2.geographicRegion ="sample data2";
premiumMaster2.specPgmProcessCd ="sample data2";
premiumMaster2.adFeeGlCode ="sample data2";
premiumMaster2.adFeeCompCode ="sample data2";
premiumMaster2.adminFee =123;
premiumMaster2.pctOfMatrix =123;
premiumMaster2.matrixDef ="sample data2";
premiumMaster2.pctAllowed =123;
premiumMaster2.priceOrAdjudicate ="sample data2";
premiumMaster2.pctOfBilled =123;
premiumMaster2.priceSchedule2 ="sample data2";
premiumMaster2.priceSchedule1 ="sample data2";
premiumMaster2.priceRule2 ="sample data2";
premiumMaster2.priceRule1 ="sample data2";
premiumMaster2.rate5 =123;
premiumMaster2.rate4 =123;
premiumMaster2.rate3 =123;
premiumMaster2.rate2 =123;
premiumMaster2.rate1 =123;
premiumMaster2.tieringMethod ="sample data2";
premiumMaster2.glRefCode ="sample data2";
premiumMaster2.companyCode ="sample data2";
premiumMaster2.lineOfBusiness ="sample data2";
premiumMaster2.benefitPackageId ="sample data2";
premiumMaster2.endDate =new Date('2010-01-01');
premiumMaster2.effectiveDate =new Date('2010-01-01');
premiumMaster2.planRiderCode ="sample data2";
premiumMaster2.recordType ="sample data2";
premiumMaster2.seqGroupId =123;
premiumMaster2.seqPremId =123;

var premiumMaster3 = new PremiumMaster();
premiumMaster3.excludeCapClmDtl ="sample data3";
premiumMaster3.dentalCobCalcMethod ="sample data3";
premiumMaster3.claimFilingIndicator ="sample data3";
premiumMaster3.rateModifyDate =new Date('2010-01-01');
premiumMaster3.cobExcludeCapClaimCode ="sample data3";
premiumMaster3.cobPolicyFlag ="sample data3";
premiumMaster3.depDetermRuleCode ="sample data3";
premiumMaster3.instCobCalcMethod ="sample data3";
premiumMaster3.rateCategory ="sample data3";
premiumMaster3.commissionGlRefCode ="sample data3";
premiumMaster3.commissionCompanyCode ="sample data3";
premiumMaster3.commissionMatrixDef ="sample data3";
premiumMaster3.cobCalcMethod ="sample data3";
premiumMaster3.reasonCode ="sample data3";
premiumMaster3.applyPcp ="sample data3";
premiumMaster3.exclusionPeriod =123;
premiumMaster3.exclusionType ="sample data3";
premiumMaster3.adFeeLevelCode ="sample data3";
premiumMaster3.updateProcess ="sample data3";
premiumMaster3.updateUser ="sample data3";
premiumMaster3.updateDatetime =new Date('2010-01-01');
premiumMaster3.insertProcess ="sample data3";
premiumMaster3.insertUser ="sample data3";
premiumMaster3.insertDatetime =new Date('2010-01-01');
premiumMaster3.securityCode ="sample data3";
premiumMaster3.geographicRegion ="sample data3";
premiumMaster3.specPgmProcessCd ="sample data3";
premiumMaster3.adFeeGlCode ="sample data3";
premiumMaster3.adFeeCompCode ="sample data3";
premiumMaster3.adminFee =123;
premiumMaster3.pctOfMatrix =123;
premiumMaster3.matrixDef ="sample data3";
premiumMaster3.pctAllowed =123;
premiumMaster3.priceOrAdjudicate ="sample data3";
premiumMaster3.pctOfBilled =123;
premiumMaster3.priceSchedule2 ="sample data3";
premiumMaster3.priceSchedule1 ="sample data3";
premiumMaster3.priceRule2 ="sample data3";
premiumMaster3.priceRule1 ="sample data3";
premiumMaster3.rate5 =123;
premiumMaster3.rate4 =123;
premiumMaster3.rate3 =123;
premiumMaster3.rate2 =123;
premiumMaster3.rate1 =123;
premiumMaster3.tieringMethod ="sample data3";
premiumMaster3.glRefCode ="sample data3";
premiumMaster3.companyCode ="sample data3";
premiumMaster3.lineOfBusiness ="sample data3";
premiumMaster3.benefitPackageId ="sample data3";
premiumMaster3.endDate =new Date('2010-01-01');
premiumMaster3.effectiveDate =new Date('2010-01-01');
premiumMaster3.planRiderCode ="sample data3";
premiumMaster3.recordType ="sample data3";
premiumMaster3.seqGroupId =123;
premiumMaster3.seqPremId =123;


export const PremiumMasters: PremiumMaster[] = [
    premiumMaster1,
    premiumMaster2,
    premiumMaster3,
];