/* Copyright (c) 2020 . All Rights Reserved. */

import { Injectable } from '@angular/core';
import { Http, Response, URLSearchParams, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { Headers } from '@angular/http';
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/map';
import { SecUser} from "../../api-models"

var secUser1 = new SecUser();
secUser1.termReason ="sample data1";
secUser1.termDate =new Date('2010-01-01');
secUser1.effDate =new Date('2010-01-01');
secUser1.qSupervisorPriv ="sample data1";
secUser1.usePwdProfInd ="sample data1";
secUser1.resetPwdInd ="sample data1";
secUser1.userDate2 =new Date('2010-01-01');
secUser1.userDate1 =new Date('2010-01-01');
secUser1.userDefined2 ="sample data1";
secUser1.userDefined1 ="sample data1";
secUser1.sfldlId ="sample data1";
secUser1.languageId =123;
secUser1.noteSecurityLevel ="sample data1";
secUser1.usrSecurityLevel ="sample data1";
secUser1.templateFlg ="sample data1";
secUser1.usrLocation ="sample data1";
secUser1.curUsrDept ="sample data1";
secUser1.description ="sample data1";
secUser1.userType ="sample data1";
secUser1.dfltTemplate ="sample data1";
secUser1.updateProcess ="sample data1";
secUser1.updateUser ="sample data1";
secUser1.updateDatetime =new Date('2010-01-01');
secUser1.insertProcess ="sample data1";
secUser1.insertUser ="sample data1";
secUser1.insertDatetime =new Date('2010-01-01');
secUser1.secId ="sample data1";
secUser1.suPriv ="sample data1";
secUser1.provAffil ="sample data1";
secUser1.ipaAffil ="sample data1";
secUser1.grpAffil ="sample data1";
secUser1.pendClaimOvr ="sample data1";
secUser1.claimLimit =123;
secUser1.loginMenu ="sample data1";
secUser1.fax ="sample data1";
secUser1.ext ="sample data1";
secUser1.tel ="sample data1";
secUser1.initials ="sample data1";
secUser1.lname ="sample data1";
secUser1.mi ="sample data1";
secUser1.fname ="sample data1";
secUser1.userId ="sample data1";

var secUser2 = new SecUser();
secUser2.termReason ="sample data2";
secUser2.termDate =new Date('2010-01-01');
secUser2.effDate =new Date('2010-01-01');
secUser2.qSupervisorPriv ="sample data2";
secUser2.usePwdProfInd ="sample data2";
secUser2.resetPwdInd ="sample data2";
secUser2.userDate2 =new Date('2010-01-01');
secUser2.userDate1 =new Date('2010-01-01');
secUser2.userDefined2 ="sample data2";
secUser2.userDefined1 ="sample data2";
secUser2.sfldlId ="sample data2";
secUser2.languageId =123;
secUser2.noteSecurityLevel ="sample data2";
secUser2.usrSecurityLevel ="sample data2";
secUser2.templateFlg ="sample data2";
secUser2.usrLocation ="sample data2";
secUser2.curUsrDept ="sample data2";
secUser2.description ="sample data2";
secUser2.userType ="sample data2";
secUser2.dfltTemplate ="sample data2";
secUser2.updateProcess ="sample data2";
secUser2.updateUser ="sample data2";
secUser2.updateDatetime =new Date('2010-01-01');
secUser2.insertProcess ="sample data2";
secUser2.insertUser ="sample data2";
secUser2.insertDatetime =new Date('2010-01-01');
secUser2.secId ="sample data2";
secUser2.suPriv ="sample data2";
secUser2.provAffil ="sample data2";
secUser2.ipaAffil ="sample data2";
secUser2.grpAffil ="sample data2";
secUser2.pendClaimOvr ="sample data2";
secUser2.claimLimit =123;
secUser2.loginMenu ="sample data2";
secUser2.fax ="sample data2";
secUser2.ext ="sample data2";
secUser2.tel ="sample data2";
secUser2.initials ="sample data2";
secUser2.lname ="sample data2";
secUser2.mi ="sample data2";
secUser2.fname ="sample data2";
secUser2.userId ="sample data2";

var secUser3 = new SecUser();
secUser3.termReason ="sample data3";
secUser3.termDate =new Date('2010-01-01');
secUser3.effDate =new Date('2010-01-01');
secUser3.qSupervisorPriv ="sample data3";
secUser3.usePwdProfInd ="sample data3";
secUser3.resetPwdInd ="sample data3";
secUser3.userDate2 =new Date('2010-01-01');
secUser3.userDate1 =new Date('2010-01-01');
secUser3.userDefined2 ="sample data3";
secUser3.userDefined1 ="sample data3";
secUser3.sfldlId ="sample data3";
secUser3.languageId =123;
secUser3.noteSecurityLevel ="sample data3";
secUser3.usrSecurityLevel ="sample data3";
secUser3.templateFlg ="sample data3";
secUser3.usrLocation ="sample data3";
secUser3.curUsrDept ="sample data3";
secUser3.description ="sample data3";
secUser3.userType ="sample data3";
secUser3.dfltTemplate ="sample data3";
secUser3.updateProcess ="sample data3";
secUser3.updateUser ="sample data3";
secUser3.updateDatetime =new Date('2010-01-01');
secUser3.insertProcess ="sample data3";
secUser3.insertUser ="sample data3";
secUser3.insertDatetime =new Date('2010-01-01');
secUser3.secId ="sample data3";
secUser3.suPriv ="sample data3";
secUser3.provAffil ="sample data3";
secUser3.ipaAffil ="sample data3";
secUser3.grpAffil ="sample data3";
secUser3.pendClaimOvr ="sample data3";
secUser3.claimLimit =123;
secUser3.loginMenu ="sample data3";
secUser3.fax ="sample data3";
secUser3.ext ="sample data3";
secUser3.tel ="sample data3";
secUser3.initials ="sample data3";
secUser3.lname ="sample data3";
secUser3.mi ="sample data3";
secUser3.fname ="sample data3";
secUser3.userId ="sample data3";


export const SecUsers: SecUser[] = [
    secUser1,
    secUser2,
    secUser3,
];