/* Copyright (c) 2020 . All Rights Reserved. */

import {GroupMaster} from "../group-master.model";
import {LineOfBusinessMaster} from "../line-of-business-master.model";
import {MemberMaster} from "../member-master.model";
import {PlanMaster} from "../plan-master.model";
import {VendorMaster} from "../vendor-master";
import {ProvMaster} from "../prov-master.model";
import {ProvContract} from "../prov-contract.model";
import {ProfsvcClaimDetail} from "./profsvc-claim-detail.model";
import {DiagnosisCodeMaster} from "../diagnosis-code-master.model";
import {ProfsvcClaimHdrRemarks} from "./profsvc-claim-hdr-remarks.model";
import {ProfsvcClaimLenrx} from "./profsvc-claim-lenrx.model";
import {AuthMaster} from "../authorization/auth-master.model";

export class ProfsvcClaimHeader {
    diagnosis3: string;
    diagnosis4: string;
    dateReceived: string;
    userDefined1: string;
    userDefined2: string;
    batchNumber: string;
    securityCode: string;
    insertDatetime: string;
    insertUser: string;
    insertProcess: string;
    updateDatetime: string;
    updateUser: string;
    updateProcess: string;
    seqProvContract: number;
    paySubscriber: string;
    submittedAuthNumber: number;
    submittedSecondaryAuth: string;
    otherInsuranceInd: string;
    assignOfBenefits: string;
    emplRelatedInd: string;
    accidentInd: string;
    accidentSymptomDate: string;
    patControlNo: string;
    provAssignInd: string;
    facilityLabIdNo: string;
    sameSimilarSymptomInd: string;
    sameSimilarSymptomDate: string;
    admissionDate1: string;
    dischargeDate1: string;
    covProvFlag: string;
    seqCovProvParent: number;
    reimbMethod: string;
    coveringMethod: string;
    origSeqProvContract: number;
    ocCarrierCode: string;
    cobAlwdAmtRule: string;
    cobAlwdAmtRsn: string;
    authLevel: string;
    unableToWorkBeginDate: string;
    unableToWorkThruDate: string;
    reservedLocalUseHdr: string;
    outsideLabInd: string;
    outsideLabCharges: number;
    medicaidResubmitCode: string;
    originalReferenceNumber: string;
    patientPaidAmount: number;
    facilityNumber: string;
    labNumber: string;
    autoAccidentIn: string;
    autoAccidentState: string;
    releaseMedRecsInd: string;
    onsetTime: string;
    authWaiveMethod: string;
    seqClaimId: number;
    claimNumber: string;
    primarySvcDate: string | any;
    claimThruDate: string;
    authNumber: number;
    secondaryAuth: string;
    seqMembId: number;
    memberAge: number;
    memberGender: string;
    seqPcpId: number;
    pcpType: string;
    pcpSpec: string;
    pcpIpaId: string;
    seqGroupId: number;
    planCode: string;
    lineOfBusiness: string;
    panelId: string;
    riderString: string;
    eligibleThruDate: string;
    eligStatus: string;
    seqProvId: number;
    seqProvAddress: number;
    providerParStat: string;
    providerType: string;
    providerSpec: string;
    providerIpaId: string;
    providerPcpFlag: string;
    seqRefProvId: number;
    refProvType: string;
    refProvSpec: string;
    refProvParStat: string;
    refProvIpaId: string;
    seqVendId: number;
    seqVendAddress: number;
    totalBilledAmt: number;
    placeOfService1: string;
    placeOfService2: string;
    placeOfService3: string;
    serviceReason1: string;
    diagnosis1: string;
    diagnosis2: string;
    providerPanel: string;
    providerIpa: string;
    authClass: string;
    refProvPcp: string;
    auditStatus: string;
    authMatchOrder: number;
    seqDfltVendId: number;
    seqDfltVendAddress: number;
    seqPaySubVendId: number;
    seqPaySubVendAddrId: number;
    acceptMedicareAssignFlag: string;
    explanationAttached: string;
    inServiceArea: string;
    providerPostalCode: string;
    headerChanged: string;
    primaryOcExists: string;
    payDependent: string;
    invalidDataInd: string;
    privacyApplies: string;
    seqMcondId: number;
    memberDateOfDeath: string;
    memberWeightPounds: number;
    memberPregnancyInd: string;
    spinalManipInitTreatment: string;
    spinalManipConditionCode: string;
    spinalManipDesc1: string;
    spinalManipDesc2: string;
    spinalManipXrayAvailibility: string;
    footCareLastVisitDate: string;
    mammographyCertNo: string;
    epsdtReferral: string;
    epsdtConditionInd1: string;
    epsdtConditionInd2: string;
    epsdtConditionInd3: string;
    relInfoSign: string;
    signRendProv: string;
    diagnosis5: string;
    diagnosis6: string;
    diagnosis7: string;
    diagnosis8: string;
    claimSubmReasonCode: string;
    memberState: string;


    diagnosisCodeMasterDiagnosis1: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis2: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis3: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis4: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis5: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis6: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis7: DiagnosisCodeMaster;
    diagnosisCodeMasterDiagnosis8: DiagnosisCodeMaster;

    groupMaster: GroupMaster;

    lineOfBusinessMaster: LineOfBusinessMaster;

    memberMaster: MemberMaster;

    planMaster: PlanMaster;

    profsvcClaimHdrRemark: ProfsvcClaimHdrRemarks;
    profsvcClaimLenrxes: ProfsvcClaimLenrx;
    profsvcClaimDetails: ProfsvcClaimDetail[];

    provAddressSeqProvAddress;
    vendorMaster: VendorMaster;

    provContract: ProvContract;
    provMaster: ProvMaster;
    provMasterSeqProvId: ProvMaster;
    provMasterSeqVendId: ProvMaster;
    authMaster: AuthMaster;
    insertDatetimeDisplay: string;
    updateDatetimeDisplay: string;
}
