export class AccountsPayableVendorLookupLookup {
    public static ACCOUNTS_PAYABLE_VENDOR_DEFAULT = [
        {headerName: 'AP Status', field: 'AP_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Status', field: 'CLAIM_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'SELECT FOR PAYMENT', field: 'SELECT_FOR_PAYMENT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Service Date', field: 'PRIMARY_SVC_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diamond ID', field: 'DIAMOND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Amount', field: 'BILLED_AMT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq AP Trans', field: 'SEQ_AP_TRANS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vendor ID', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vendor Address', field: 'SEQ_VEND_ADDRESS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Number', field: 'CHECK_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'CHECK_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Prov ID', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Subs ID', field: 'SEQ_SUBS_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Detail Service Date', field: 'DETAIL_SVC_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Date Time', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Claim ID', field: 'SEQ_CLAIM_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Line Number', field: 'LINE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Sub Line ', field: 'SUB_LINE_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Person Number', field: 'PERSON_NUMBER', width: 140, headerClass: 'font-weight-bold'}
        ];
    public static ACCOUNTS_PAYABLE_VENDOR_ALL = [
        {headerName: 'AP Status', field: 'AP_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Status', field: 'CLAIM_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'SELECT FOR PAYMENT', field: 'SELECT_FOR_PAYMENT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Service Date', field: 'PRIMARY_SVC_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diamond ID', field: 'DIAMOND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Amount', field: 'BILLED_AMT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq AP Trans', field: 'SEQ_AP_TRANS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vendor ID', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vendor Address', field: 'SEQ_VEND_ADDRESS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Number', field: 'CHECK_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'CHECK_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Prov ID', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Subs ID', field: 'SEQ_SUBS_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Detail Service Date', field: 'DETAIL_SVC_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Date Time', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Claim ID', field: 'SEQ_CLAIM_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Line Number', field: 'LINE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Sub Line ', field: 'SUB_LINE_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Person Number', field: 'PERSON_NUMBER', width: 140, headerClass: 'font-weight-bold'}
    ];

    public static ACCOUNTS_PAYABLE_VENDOR_DISPLAY_DEFAULT = [
        {headerName: 'Provider Name', field: 'PROVIDER_NAME', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Amt', field: 'BILLED_AMT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'DOS', field: 'DOS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'DIAMOND ID', field: 'DIAMOND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Name', field: 'MEMBER_NAME', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'PN', field: 'PN', width: 40, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'AP', field: 'AP', width: 60, headerClass: 'font-weight-bold'},
        {headerName: 'Claim', field: 'CLAIM', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Pymt', field: 'PYMT', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Entered', field: 'ENTERED', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Trans No.', field: 'TRANS_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check No.', field: 'CHECK_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'CHECK_DATE', width: 140, headerClass: 'font-weight-bold'},
    ];

    public static ACCOUNTS_PAYABLE_VENDOR_DISPLAY_ALL = [
        {headerName: 'Provider Name', field: 'PROVIDER_NAME', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Amt', field: 'BILLED_AMT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'DOS', field: 'DOS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'DIAMOND ID', field: 'DIAMOND_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Name', field: 'MEMBER_NAME', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'PN', field: 'PN', width: 40, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'AP', field: 'AP', width: 60, headerClass: 'font-weight-bold'},
        {headerName: 'Claim', field: 'CLAIM', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Pymt', field: 'PYMT', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Entered', field: 'ENTERED', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Trans No.', field: 'TRANS_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check No.', field: 'CHECK_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'CHECK_DATE', width: 140, headerClass: 'font-weight-bold'},
    ]
}
