export class AccountsPayableLookup {
    public static ACCOUNTS_PAYABLE_DEFAULT = [
        {headerName: 'Seq AP Transaction', field: 'seqApTrans', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Type', field: 'fileType', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'AP Status', field: 'apStatus', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Print Flag', field: 'printFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Withhold', field: 'discountWithhold', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Net Amount', field: 'netAmt', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Select For Payment', field: 'selectForPayment', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Number', field: 'checkNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'checkDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Due Date', field: 'dueDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Posted Date', field: 'postedDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor 1099 Flag', field: 'vendor1099Flag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Company Code', field: 'companyCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Bank Act', field: 'bankAccount', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Debit GL Number 1', field: 'debitGlNumber1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Debit GL Number 2', field: 'debitGlNumber2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Credit GL Number 1', field: 'creditGlNumber1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Credit GL Number 2', field: 'creditGlNumber2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'AP Type', field: 'apType', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'GL Month', field: 'glMonth', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Pre Price', field: 'prePriceOnlyFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vend Address', field: 'seqVendAddress', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'EFT Trans Number', field: 'eftTransNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Interest Debit G/L Number', field: 'intDebitGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Interest Credit G/L Number', field: 'intCreditGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Debit G/L Number', field: 'dscntDebitGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Credit G/L Number', field: 'dscntCreditGlNumber', width: 140, headerClass: 'font-weight-bold'}
    ];
    public static ACCOUNTS_PAYABLE_ALL = [
        {headerName: 'Seq AP Transaction', field: 'seqApTrans', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Type', field: 'fileType', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'AP Status', field: 'apStatus', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Print Flag', field: 'printFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Withhold', field: 'discountWithhold', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Net Amount', field: 'netAmt', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Select For Payment', field: 'selectForPayment', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Number', field: 'checkNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Check Date', field: 'checkDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Due Date', field: 'dueDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Posted Date', field: 'postedDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor 1099 Flag', field: 'vendor1099Flag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Company Code', field: 'companyCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Bank Act', field: 'bankAccount', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Debit GL Number 1', field: 'debitGlNumber1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Debit GL Number 2', field: 'debitGlNumber2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Credit GL Number 1', field: 'creditGlNumber1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Credit GL Number 2', field: 'creditGlNumber2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'AP Type', field: 'apType', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'GL Month', field: 'glMonth', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Pre Price', field: 'prePriceOnlyFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Vend Address', field: 'seqVendAddress', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'EFT Trans Number', field: 'eftTransNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Interest Debit G/L Number', field: 'intDebitGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Interest Credit G/L Number', field: 'intCreditGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Debit G/L Number', field: 'dscntDebitGlNumber', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discount Credit G/L Number', field: 'dscntCreditGlNumber', width: 140, headerClass: 'font-weight-bold'}
        ];
}