export class DiagnosisMasterLookup {
    public static DEFAULT = [
        {headerName: 'Diagnosis Code', field: 'diagnosisCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Short Description', field: 'shortDescription', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Description', field: 'description', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 1', field: 'dxClass1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 2', field: 'dxClass2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 3', field: 'dxClass3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'From Age', field: 'fromAge', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'To Age', field: 'toAge', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Patient Gender', field: 'patientGender', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Trauma Flag', field: 'traumaFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Management', field: 'caseManagement', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure Class', field: 'procedureClass', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Mdc Code', field: 'mdcCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Edit Flag', field: 'editFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Open Procedure Flag', field: 'openProcedureFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Security Code', field: 'securityCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Datetime', field: 'insertDatetime', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert User', field: 'insertUser', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Process', field: 'insertProcess', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update Datetime', field: 'updateDatetime', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update User', field: 'updateUser', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update Process', field: 'updateProcess', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Drg Default Birthweight', field: 'drgDefaultBirthweight', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Effective Date', field: 'effectiveDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Term Date', field: 'termDate', width: 140, headerClass: 'font-weight-bold'}
    ];

    public static ALL = [
        {headerName: 'Short Description', field: 'shortDescription', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Description', field: 'description', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 1', field: 'dxClass1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 2', field: 'dxClass2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Dx Class 3', field: 'dxClass3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'From Age', field: 'fromAge', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'To Age', field: 'toAge', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Patient Gender', field: 'patientGender', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Trauma Flag', field: 'traumaFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Management', field: 'caseManagement', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure Class', field: 'procedureClass', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Mdc Code', field: 'mdcCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Edit Flag', field: 'editFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Open Procedure Flag', field: 'openProcedureFlag', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Security Code', field: 'securityCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Datetime', field: 'insertDatetime', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert User', field: 'insertUser', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Insert Process', field: 'insertProcess', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update Datetime', field: 'updateDatetime', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update User', field: 'updateUser', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Drg Default Birthweight', field: 'drgDefaultBirthweight', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Update Process', field: 'updateProcess', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Effective Date', field: 'effectiveDate', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Term Date', field: 'termDate', width: 140, headerClass: 'font-weight-bold'}
    ];
}
