export class GroupMasterLookup {

    public static GROUP_MASTER_DEFAULT = [{headerName: 'Group ID', field: 'groupId', width: 150, headerClass: 'font-weight-bold'},
        {headerName: 'Short Name', field: 'shortName', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Level', field: 'levelCode', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Group ID', field: 'seqGroupId', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Parent ID', field: 'seqParentId', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name1', field: 'groupName1', width: 160, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name2', field: 'groupName2', width: 160, headerClass: 'font-weight-bold'},
        {headerName: 'Address Line1', field: 'addressLine1', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Address Line2', field: 'addressLine2', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'City', field: 'city', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'State', field: 'state', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'zipCode', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Group Type', field: 'groupType', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Sic Code', field: 'sicCode', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'User Defined1', field: 'userDefined1', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'User Defined2', field: 'userDefined2', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Proration Method', field: 'prorationMethod', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Level', field: 'billingLevel', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Batch', field: 'billingBatch', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'No Of Retro Months', field: 'noOfRetroMonths', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Through Date', field: 'billedThroughDate', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Grace Period', field: 'gracePeriod', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Sort Option', field: 'sortOption', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Next Open Start Dt', field: 'nextOpenStartDt', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Next Open End Date', field: 'nextOpenEndDate', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Reason', field: 'holdReason', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Date', field: 'holdDate', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Security Code', field: 'securityCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Country', field: 'country', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Common Billing Date', field: 'commonBillingDate', width: 220, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Cycle', field: 'billingCycle', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'National Employer Id', field: 'nationalEmployerId', width: 230, headerClass: 'font-weight-bold'}];

    public static GROUP_MASTER_ALL = [
        {headerName: 'Level Code', field: 'levelCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Seq Parent Id', field: 'seqGroupId', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name1', field: 'groupName1', width: 160, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name2', field: 'groupName2', width: 160, headerClass: 'font-weight-bold'},
        {headerName: 'Address Line1', field: 'addressLine1', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Address Line2', field: 'addressLine2', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'City', field: 'city', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'State', field: 'state', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'zipCode', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Group Type', field: 'groupType', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Sic Code', field: 'sicCode', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'User Defined1', field: 'userDefined1', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'User Defined2', field: 'userDefined2', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Proration Method', field: 'prorationMethod', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Level', field: 'billingLevel', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Batch', field: 'billingBatch', width: 180, headerClass: 'font-weight-bold'},
        {headerName: 'No Of Retro Months', field: 'noOfRetroMonths', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Billed Through Date', field: 'billedThroughDate', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Grace Period', field: 'gracePeriod', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Sort Option', field: 'sortOption', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Next Open Start Dt', field: 'nextOpenStartDt', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Next Open End Date', field: 'nextOpenEndDate', width: 200, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Reason', field: 'holdReason', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Date', field: 'holdDate', width: 120, headerClass: 'font-weight-bold'},
        {headerName: 'Security Code', field: 'securityCode', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Country', field: 'country', width: 100, headerClass: 'font-weight-bold'},
        {headerName: 'Common Billing Date', field: 'commonBillingDate', width: 220, headerClass: 'font-weight-bold'},
        {headerName: 'Billing Cycle', field: 'billingCycle', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'National Employer Id', field: 'nationalEmployerId', width: 230, headerClass: 'font-weight-bold'}
    ];
}
