export class InstitutionalAuthNumberLookup {
    public static DEFAULT = [
        {headerName: 'Auth Number', field: 'AUTH_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Secondary Auth No', field: 'AUTH_SECONDARY_AUTH_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Type', field: 'AUTH_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Level', field: 'AUTH_LEVEL', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Requested Date', field: 'REQUESTED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber Id', field: 'MEMBER_SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Person Number', field: 'MEMBER_PERSON_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Last Name', field: 'MEMBER_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS Last Name', field: 'AUTH_NS_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'MEMBER_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS First Name', field: 'AUTH_NS_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS Subscriber Id', field: 'AUTH_NS_SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Short Name', field: 'GROUP_SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Plan Code', field: 'AUTH_PLAN_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Age', field: 'AUTH_MEMBER_AGE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Gender', field: 'AUTH_MEMBER_GENDER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Intake Date Time', field: 'AUTH_INTAKE_DATE_TIME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Caller Name', field: 'AUTH_CALLER_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Caller Phone Number', field: 'AUTH_CALLER_PHONE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Patient Acct No', field: 'AUTH_PATIENT_ACC_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Medical Rec No', field: 'AUTH_MEDICAL_REC_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Admit Primary Date', field: 'AUTH_ADMIT_PRIMARY_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Estimated Cost', field: 'AUTH_ESTIMATED_COST', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Expiration Date', field: 'AUTH_EXPIRATION_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 1', field: 'AUTH_DIAGNOSIS1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 1 Text', field: 'AUTH_DIAGNOSIS1_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 2', field: 'AUTH_DIAGNOSIS2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 2 Text', field: 'AUTH_DIAGNOSIS2_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 3', field: 'AUTH_DIAGNOSIS3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 3 Text', field: 'AUTH_DIAGNOSIS3_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 1', field: 'AUTH_SURG_PROCEDURE1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 1 Date', field: 'AUTH_SURG_PROCEDURE1_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 2', field: 'AUTH_SURG_PROCEDURE2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 2 Date', field: 'AUTH_SURG_PROCEDURE2_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 3', field: 'AUTH_SURG_PROCEDURE3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 3 Date', field: 'AUTH_SURG_PROCEDURE3_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Review Type', field: 'AUTH_REVIEW_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Reviewer', field: 'AUTH_REVIEWER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Review Date', field: 'AUTH_FIRST_REVIEW_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Next Review Date', field: 'AUTH_NEXT_REVIEW_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Service Admit Type', field: 'AUTH_SERVICE_ADMIT_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Service Reason', field: 'AUTH_SERVICE_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Place Of Service', field: 'AUTH_PLACE_OF_SERVICE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Med Def Code', field: 'AUTH_MED_DEF_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Overall Status', field: 'AUTH_OVERALL_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Status Date', field: 'AUTH_STATUS_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Reason', field: 'AUTH_HOLD_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Date', field: 'AUTH_HOLD_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Closed Reason', field: 'AUTH_CLOSED_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Closed Date', field: 'AUTH_CLOSED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Reason', field: 'AUTH_DENIED_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Date', field: 'AUTH_DENIED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Second Opinion Req', field: 'AUTH_SECOND_OPINION_REQ', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Norm Days Visits', field: 'AUTH_NORM_DAYS_VISITS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Req Days Visits', field: 'AUTH_REQ_DAYS_VISITS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Authorized Days Vis', field: 'AUTH_AUTHORIZED_DAYS_VIS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Days Vis', field: 'AUTH_DENIED_DAYS_VIS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Authorized Cost', field: 'AUTH_AUTHORIZED_COST', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prior Day Admit', field: 'AUTH_PRIOR_DAY_ADMIT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discharge Diagnosis', field: 'AUTH_DISCHARGE_DIAGNOSIS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Disch Thru Date', field: 'AUTH_DISCH_THRU_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Outcome', field: 'AUTH_OUTCOME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Impact', field: 'AUTH_IMPACT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Disposition', field: 'AUTH_DISPOSITION', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Manager', field: 'AUTH_CASE_MANAGER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Number', field: 'AUTH_CASE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Referral Date', field: 'AUTH_CASE_REFERRAL_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Tpl Code', field: 'AUTH_TPL_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prov Code', field: 'PROV_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prov Last Name', field: 'PROV_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prov First Name', field: 'PROV_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'}
    ];

    public static ALL = [
        {headerName: 'Auth Type', field: 'AUTH_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prov Code', field: 'PROV_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Last Name', field: 'PROV_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Name', field: 'PROV_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Requested Date', field: 'REQUESTED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber Id', field: 'MEMBER_SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Person Number', field: 'MEMBER_PERSON_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Last Name', field: 'MEMBER_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member irst Name', field: 'MEMBER_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member IPA ID', field: 'MEMBER_ELIG_IPA_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS Subscriber Id', field: 'AUTH_NS_SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS Last Name', field: 'AUTH_NS_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'NS First Name', field: 'AUTH_NS_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group Short Name', field: 'GROUP_SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Plan Code', field: 'AUTH_PLAN_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Age', field: 'AUTH_MEMBER_AGE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Gender', field: 'AUTH_MEMBER_GENDER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Intake Date Time', field: 'AUTH_INTAKE_DATE_TIME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Caller Name', field: 'AUTH_CALLER_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Caller Phone Number', field: 'AUTH_CALLER_PHONE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Patient Acct No', field: 'AUTH_PATIENT_ACC_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Medical Rec No', field: 'AUTH_MEDICAL_REC_NO', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Admit Primary Date', field: 'AUTH_ADMIT_PRIMARY_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Estimated Cost', field: 'AUTH_ESTIMATED_COST', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Expiration Date', field: 'AUTH_EXPIRATION_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 1', field: 'AUTH_DIAGNOSIS1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 1 Text', field: 'AUTH_DIAGNOSIS1_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 2', field: 'AUTH_DIAGNOSIS2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 2 Text', field: 'AUTH_DIAGNOSIS2_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 3', field: 'AUTH_DIAGNOSIS3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Diagnosis 3 Text', field: 'AUTH_DIAGNOSIS3_TEXT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 1', field: 'AUTH_SURG_PROCEDURE1', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 1 Date', field: 'AUTH_SURG_PROCEDURE1_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 2', field: 'AUTH_SURG_PROCEDURE2', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 2 Date', field: 'AUTH_SURG_PROCEDURE2_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Surg Procedure 3', field: 'AUTH_SURG_PROCEDURE3', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Procedure 3 Date', field: 'AUTH_SURG_PROCEDURE3_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Review Type', field: 'AUTH_REVIEW_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Reviewer', field: 'AUTH_REVIEWER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'First Review Date', field: 'AUTH_FIRST_REVIEW_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Next Review Date', field: 'AUTH_NEXT_REVIEW_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Late Notification', field: 'AUTH_LATE_NOTIFICATION', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Service Admit Type', field: 'AUTH_SERVICE_ADMIT_TYPE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Service Reason', field: 'AUTH_SERVICE_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Place Of Service', field: 'AUTH_PLACE_OF_SERVICE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Med Def Code', field: 'AUTH_MED_DEF_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Overall Status', field: 'AUTH_OVERALL_STATUS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Status Date', field: 'AUTH_STATUS_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Reason', field: 'AUTH_HOLD_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hold Date', field: 'AUTH_HOLD_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Closed Reason', field: 'AUTH_CLOSED_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Closed Date', field: 'AUTH_CLOSED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Reason', field: 'AUTH_DENIED_REASON', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Date', field: 'AUTH_DENIED_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Second Opinion Req', field: 'AUTH_SECOND_OPINION_REQ', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Norm Days Visits', field: 'AUTH_NORM_DAYS_VISITS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Req Days Visits', field: 'AUTH_REQ_DAYS_VISITS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Denied Days Vis', field: 'AUTH_DENIED_DAYS_VIS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Authorized Cost', field: 'AUTH_AUTHORIZED_COST', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prior Day Admit', field: 'AUTH_PRIOR_DAY_ADMIT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discharge Diagnosis', field: 'AUTH_DISCHARGE_DIAGNOSIS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Disch Thru Date', field: 'AUTH_DISCH_THRU_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Outcome', field: 'AUTH_OUTCOME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Impact', field: 'AUTH_IMPACT', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Disposition', field: 'AUTH_DISPOSITION', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Manager', field: 'AUTH_CASE_MANAGER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Number', field: 'AUTH_CASE_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Case Referral Date', field: 'AUTH_CASE_REFERRAL_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Tpl Code', field: 'AUTH_TPL_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    ];
}
