export class InstClaimHeaderClaimNumberLookup {
    public static DEFAULT = [
        {headerName: 'Sequential Claim ID', field: 'SEQUENTIAL_CLAIM_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Number', field: 'CLAIM_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Admit Date', field: 'ADMIT_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Discharge Date', field: 'DISCHARGE_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'P/N', field: 'PN', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Last Name', field: 'MEMBER_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member First Name', field: 'MEMBER_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Provider Name', field: 'PROVIDER_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'In Svc Area', field: 'IN_SVC_AREA', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor ID', field: 'VENDOR_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor Name', field: 'VENDOR_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Number', field: 'AUTH_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Attending Provider ID', field: 'ATTENDING_PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name', field: 'GROUP_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'IPA ID', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Line Of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Panel ID', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'EOB Ind', field: 'EOB_IND', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hdr Chgd', field: 'HDR_CHGD', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Accept Medicare', field: 'ACCEPT_MEDICARE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Oc', field: 'PRIMARY_OC', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Batch Number', field: 'BATCH_NUMBER', width: 140, headerClass: 'font-weight-bold'},
    ];
    public static ALL = [
        {headerName: 'Claim Thru Date', field: 'CLAIM_THRU_DATE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Person Number', field: 'PERSON_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member Last Name', field: 'MEMBER_LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Member First Name', field: 'MEMBER_FIRST_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Prov Master A Provider Id', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor ID', field: 'VENDOR_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor Name', field: 'VENDOR_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Number', field: 'AUTH_NUMBER', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name', field: 'GROUP_NAME', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'IPA ID', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Line Of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Panel ID', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Provider Postal Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Explanation Attached', field: 'EXPLANATION_ATTACHED', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'In Service Area', field: 'IN_SVC_AREA', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Hdr Chgd', field: 'HDR_CHGD', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Accept Medicare Assign Id', field: 'ACCEPT_MEDICARE', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Oc', field: 'PRIMARY_IC', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Batch Number', field: 'BATCH_NUMBER', width: 140, headerClass: 'font-weight-bold'}
    ];
}
