export class ProcedureCodeMasterLookup {
  public static PROCEDURE_CODE_MASTER_DEFAULT = [
    {
      headerName: "Procedure Code",
      field: "procedureCode",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Short Description",
      field: "shortDescription",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Asterisk Procedure",
      field: "asteriskProcedure",
      width: 180,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Full Description",
      field: "fullDescription",
      width: 160,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Primary Grouping",
      field: "primaryGrouping",
      width: 160,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Secondary Grouping",
      field: "secondaryGrouping",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Follow Up Days",
      field: "followUpDays",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Code Class",
      field: "codeClass",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Count As Days",
      field: "countAsDays",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Hold Reason",
      field: "holdReason",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Hold Date",
      field: "holdDate",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 1",
      field: "userDefines1",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Date 1",
      field: "userDate1",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 2",
      field: "userDefines1",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Date 2",
      field: "userDate1",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Allowed Reason",
      field: "allowedReason",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "From Age",
      field: "fromAge",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "To Age",
      field: "toAge",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Paitent Gender",
      field: "paitentGender",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Security Code",
      field: "securityCode",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert DateTime",
      field: "insertDateTime",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert User",
      field: "insertUser",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert Process",
      field: "insertProcess",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update Date time",
      field: "updateDateTime",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update User",
      field: "updateUser",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update Process",
      field: "updateProcess",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Target Ref Code Flg",
      field: "targetFlag",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Price Indicator Flg",
      field: "priceIndicatorFlag",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Product Service Id Qualifier",
      field: "productServiceIdQualified",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Tooth Number Required",
      field: "toothNumberRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Surface Required",
      field: "toothNumberRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Arch Required",
      field: "ArchRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Quadrant Required",
      field: "quadrantRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Oral Cravity Required",
      field: "OralCravityRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Weighted Value",
      field: "weightedValue",
      width: 220,
      headerClass: "font-weight-bold",
    },
  ];

  public static PROCEDURE_CODE_MASTER_ALL = [
    {
      headerName: "Procedure Code",
      field: "procedureCode",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Short Description",
      field: "shortDescription",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Asterisk Procedure",
      field: "asteriskProcedure",
      width: 180,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Full Description",
      field: "fullDescription",
      width: 160,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Primary Grouping",
      field: "primaryGrouping",
      width: 160,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Secondary Grouping",
      field: "secondaryGrouping",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Follow Up Days",
      field: "followUpDays",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Code Class",
      field: "codeClass",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Count As Days",
      field: "countAsDays",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Hold Reason",
      field: "holdReason",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Hold Date",
      field: "holdDate",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 1",
      field: "userDefines1",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Date 1",
      field: "userDate1",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 2",
      field: "userDefines1",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Date 2",
      field: "userDate1",
      width: 100,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Allowed Reason",
      field: "allowedReason",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "From Age",
      field: "fromAge",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "To Age",
      field: "toAge",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Paitent Gender",
      field: "paitentGender",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Security Code",
      field: "securityCode",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert DateTime",
      field: "insertDateTime",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert User",
      field: "insertUser",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert Process",
      field: "insertProcess",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update Date time",
      field: "updateDateTime",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update User",
      field: "updateUser",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update Process",
      field: "updateProcess",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Target Ref Code Flg",
      field: "targetFlag",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Price Indicator Flg",
      field: "priceIndicatorFlag",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Product Service Id Qualifier",
      field: "productServiceIdQualified",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Tooth Number Required",
      field: "toothNumberRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Surface Required",
      field: "toothNumberRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Arch Required",
      field: "ArchRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Quadrant Required",
      field: "quadrantRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Oral Cravity Required",
      field: "OralCravityRequired",
      width: 220,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Weighted Value",
      field: "weightedValue",
      width: 220,
      headerClass: "font-weight-bold",
    },
  ];
}
