export class ProfessionalClaimServicesLookup {


    public static PROFESSIONAL_CLAIM_SERVICES_DEFAULT = [
        {headerName: 'Seq Claim ID', field: 'SEQ_CLAIM_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Number', field: 'CLAIM_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary DOS', field: 'PRIMARY_SVC_DATE', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'P/N', field: 'PERSON_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member Last Name', field: 'member_lastName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member First Name', field: 'member_firstName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider Last Name', field: 'LAST_NAME2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider First Name', field: 'FIRST_NAME3', width: 250, headerClass: 'font-weight-bold'},
        // {headerName: 'Short Name', field: 'SHORT_NAME2', width: 250, headerClass: 'font-weight-bold'},
        // {headerName: 'Provider ID', field: 'PROVIDER_ID2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'PROVIDER_POSTAL_CODE', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'In Svc Area', field: 'IN_SERVICE_AREA', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor ID', field: 'VENDOR_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor Name', field: 'SHORT_NAME', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Number', field: 'AUTH_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Second Auth', field: 'SECONDARY_AUTH', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name', field: 'GROUP_NAME_2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Ipa ID', field: 'pcpIpaId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Panel ID', field: 'PANEL_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'EOB Ind', field: 'EXPLANATION_ATTACHED', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Header Changed', field: 'HEADER_CHANGED', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Accept Medicare.', field: 'ACCEPT_MEDICARE_ASSIGN_FLAG', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Oc', field: 'PRIMARY_OC_EXISTS', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Batch Number', field: 'BATCH_NUMBER', width: 250, headerClass: 'font-weight-bold'},


    ];
    public static PROFESSIONAL_CLAIM_SERVICES_ALL = [
        {headerName: 'Seq Claim ID', field: 'SEQ_CLAIM_ID', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Number', field: 'CLAIM_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary DOS', field: 'PRIMARY_SVC_DATE', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'SUBSCRIBER_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'P/N', field: 'PERSON_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member Last Name', field: 'member_lastName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member First Name', field: 'member_firstName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider Last Name', field: 'LAST_NAME2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider First Name', field: 'FIRST_NAME3', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Short Name', field: 'SHORT_NAME2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'PROVIDER_IDB', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'PROVIDER_POSTAL_CODE', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'In Svc Area', field: 'IN_SERVICE_AREA', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor ID', field: 'VENDOR_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor Name', field: 'SHORT_NAME', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Number', field: 'AUTH_NUMBER', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Second Auth', field: 'SECONDARY_AUTH', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'GROUP_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name', field: 'GROUP_NAME_2', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Ipa ID', field: 'pcpIpaId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Panel ID', field: 'PANEL_ID', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'EOB Ind', field: 'EXPLANATION_ATTACHED', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Header Changed', field: 'HEADER_CHANGED', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Accept Medicare.', field: 'ACCEPT_MEDICARE_ASSIGN_FLAG', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Oc', field: 'PRIMARY_OC_EXISTS', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Batch Number', field: 'BATCH_NUMBER', width: 250, headerClass: 'font-weight-bold'},
    ];

    public static PROFSVC_CLAIM_HEADER_DEFAULT = [
        {headerName: 'Seq Claim ID', field: 'seqClaimId', width: 140, headerClass: 'font-weight-bold'},
        {headerName: 'Claim Number', field: 'claimNumber', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary DOS', field: 'primarySvcDate', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Subscriber ID', field: 'subscriberId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'P/N', field: 'personNumber', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member Last Name', field: 'memberLastName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Member First Name', field: 'memberFirstName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'providerId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider Last Name', field: 'providerLastName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider First Name', field: 'providerFirstName', width: 250, headerClass: 'font-weight-bold'},
        // {headerName: 'Short Name', field: 'shortName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Provider ID', field: 'getProviderIpa', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Zip Code', field: 'zipCode', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'In Svc Area', field: 'inServiceArea', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor ID', field: 'vendorId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Vendor Name', field: 'vendorName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Auth Number', field: 'authNumber', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Second Auth', field: 'secondaryAuth', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group ID', field: 'groupId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Group Name', field: 'groupName', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Ipa ID', field: 'pcpIpaId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Line of Business', field: 'lineOfBusiness', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Panel ID', field: 'panelId', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'EOB Ind', field: 'explanationAttached', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Header Changed', field: 'HEADER_CHANGED', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Accept Medicare.', field: 'ACCEPT_MEDICARE_ASSIGN_FLAG', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Primary Oc', field: 'PRIMARY_OC_EXISTS', width: 250, headerClass: 'font-weight-bold'},
        {headerName: 'Batch Number', field: 'BATCH_NUMBER', width: 250, headerClass: 'font-weight-bold'},
    ];

    public static PROFSVC_CLAIM_HEADER_ALL = ProfessionalClaimServicesLookup.PROFSVC_CLAIM_HEADER_DEFAULT;

    // public static PROFESSIONAL_CLAIM_SERVICES_ALL = [
    //     {headerName: 'Seq Claim ID', field: 'seqClaimId' , width: 140, headerClass: 'font-weight-bold'},
    //     {headerName: 'Claim Number', field: 'claimNumber', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Primary DOS', field: 'primarySvcDate', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Subscriber ID', field: 'memberMaster.subscriberId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'P/N', field: 'memberMaster.personNumber', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Member Last Name', field: 'memberMaster.lastName', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Member First Name', field: 'memberMaster.firstName', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Provider ID', field: 'provMasterA.providerId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Provider Last Name', field: 'provMasterA.lastName', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Provider First Name', field: 'provMasterA.firstName', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Zip Code', field: 'memberMaster.zipCode', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'In Svc Vendor ID Area', field: 'vendorMaster.vendorId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'In Vendor Name', field: 'vendorMaster.shortName', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Auth Number', field: 'authNumber', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Second Auth', field: 'secondaryAuth', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Group ID', field: 'groupMaster.groupId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Group Name', field: 'groupMaster.groupName1', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Ipa ID', field: 'pcpIpaId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Line of Business', field: 'lineOfBusiness', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Panel ID', field: 'panelId', width: 250, headerClass: 'font-weight-bold'},
    //     {headerName: 'Epa Ind', field: 'explanationAttached', width: 250, headerClass: 'font-weight-bold'},
    // ];
}
