export class ProviderMasterLookup {


  public static PROVIDER_MASTER_DEFAULT = [
    {headerName: 'PIMS ID', field: 'USER_DEFINED_6', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Master Speciality Type', field: 'PROVIDER_CONTRACT_SPECIALTY_TYPE', width: 300, headerClass: 'font-weight-bold'},
    {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'First Name', field: 'FIRST_NAME', width: 150, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Contract Speciality Type', field: 'SPECIALTY_TYPE', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Country', field: 'COUNTRY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 1', field: 'ADDRESS_LINE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 2', field: 'ADDRESS_LINE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'City', field: 'CITY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'State/Province', field: 'STATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Zip/Postal Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Effective Date', field: 'EFFECTIVE_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Date', field: 'TERM_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Id', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Type', field: 'PROVIDER_TYPE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Middle Initial', field: 'MIDDLE_INITIAL', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Name 2', field: 'NAME_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Category', field: 'PROVIDER_CATEGORY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Xref Id', field: 'SEQ_PROV_XREF_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id1 ', field: 'USER_ID1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id2 ', field: 'USER_ID2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id3 ', field: 'USER_ID3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Date Of Birth ', field: 'DATE_OF_BIRTH', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Non Specific Prov ', field: 'NON_SPECIFIC_PROV', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Vend Id', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 1', field: 'LANGUAGE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 2', field: 'LANGUAGE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 3', field: 'LANGUAGE_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 1', field: 'USER_DEFINED_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 2', field: 'USER_DEFINED_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 3', field: 'USER_DEFINED_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 4', field: 'USER_DEFINED_4', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 5', field: 'USER_DEFINED_5', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined Date', field: 'USER_DEFINED_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Security Code', field: 'SECURITY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Datetime', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert User', field: 'INSERT_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Process', field: 'INSERT_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Datetime', field: 'UPDATE_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update User', field: 'UPDATE_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Process', field: 'UPDATE_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Panel Id', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IPA Id', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept Existing Pat', field: 'ACCEPT_EXISTING_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'PCP Flag', field: 'PCP_FLAG', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept New Pat', field: 'ACCEPT_NEW_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'National Provider Id', field: 'NATIONAL_PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Taxonomy Code', field: 'TAXONOMY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Vendor IRS Tax ID', field: 'IRS_TAX_ID', width: 140, headerClass: 'font-weight-bold'}

    // TODO need to do all columns mappings
  ];

  public static PROVIDER_MASTER_ALL = [
    {headerName: 'PIMS ID', field: 'SEQ_PROV_XREF_ID', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Master Speciality Type', field: 'PROVIDER_CONTRACT_SPECIALTY_TYPE', width: 300, headerClass: 'font-weight-bold'},
    {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'First Name', field: 'FIRST_NAME', width: 150, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Contract Speciality Type', field: 'SPECIALTY_TYPE', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Country', field: 'COUNTRY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 1', field: 'ADDRESS_LINE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 2', field: 'ADDRESS_LINE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'City', field: 'CITY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'State/Province', field: 'STATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Zip/Postal Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Effective Date', field: 'EFFECTIVE_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Date', field: 'TERM_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Id', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Type', field: 'PROVIDER_TYPE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Middle Initial', field: 'MIDDLE_INITIAL', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Name 2', field: 'NAME_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Category', field: 'PROVIDER_CATEGORY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Xref Id', field: 'SEQ_PROV_XREF_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id1 ', field: 'USER_ID1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id2 ', field: 'USER_ID2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id3 ', field: 'USER_ID3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Date Of Birth ', field: 'DATE_OF_BIRTH', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Non Specific Prov ', field: 'NON_SPECIFIC_PROV', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Vend Id', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 1', field: 'LANGUAGE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 2', field: 'LANGUAGE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 3', field: 'LANGUAGE_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 1', field: 'USER_DEFINED_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 2', field: 'USER_DEFINED_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 3', field: 'USER_DEFINED_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 4', field: 'USER_DEFINED_4', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 5', field: 'USER_DEFINED_5', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 6', field: 'USER_DEFINED_6', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined Date', field: 'USER_DEFINED_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Security Code', field: 'SECURITY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Datetime', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert User', field: 'INSERT_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Process', field: 'INSERT_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Datetime', field: 'UPDATE_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update User', field: 'UPDATE_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Process', field: 'UPDATE_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Panel Id', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IPA Id', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept Existing Pat', field: 'ACCEPT_EXISTING_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'PCP Flag', field: 'PCP_FLAG', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept New Pat', field: 'ACCEPT_NEW_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'National Provider Id', field: 'NATIONAL_PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Taxonomy Code', field: 'TAXONOMY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Reason', field: 'TERM_REASON', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IRS Tax ID', field: 'IRS_TAX_ID', width: 140, headerClass: 'font-weight-bold'}
    // TODO need to do all columns mappings
  ];



  public static PROVIDER_MASTER_DEFAULT2 = [
    {headerName: 'PIMS ID', field: 'USER_DEFINED_6', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Master Speciality Type', field: 'SPECIALTY_TYPE', width: 300, headerClass: 'font-weight-bold'},
    {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'First Name', field: 'FIRST_NAME', width: 150, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Contract Speciality Type', field: 'PROVIDER_CONTRACT_SPECIALTY_TYPE', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Country', field: 'COUNTRY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 1', field: 'ADDRESS_LINE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 2', field: 'ADDRESS_LINE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'City', field: 'CITY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'State/Province', field: 'STATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Zip/Postal Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Effective Date', field: 'EFFECTIVE_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Date', field: 'TERM_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Id', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Type', field: 'PROVIDER_TYPE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Middle Initial', field: 'MIDDLE_INITIAL', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Name 2', field: 'NAME_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Category', field: 'PROVIDER_CATEGORY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Xref Id', field: 'SEQ_PROV_XREF_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id1 ', field: 'USER_ID1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id2 ', field: 'USER_ID2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id3 ', field: 'USER_ID3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Date Of Birth ', field: 'DATE_OF_BIRTH', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Non Specific Prov ', field: 'NON_SPECIFIC_PROV', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Vend Id', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 1', field: 'LANGUAGE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 2', field: 'LANGUAGE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 3', field: 'LANGUAGE_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 1', field: 'USER_DEFINED_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 2', field: 'USER_DEFINED_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 3', field: 'USER_DEFINED_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 4', field: 'USER_DEFINED_4', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 5', field: 'USER_DEFINED_5', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined Date', field: 'USER_DEFINED_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Security Code', field: 'SECURITY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Datetime', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert User', field: 'INSERT_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Process', field: 'INSERT_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Datetime', field: 'UPDATE_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update User', field: 'UPDATE_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Process', field: 'UPDATE_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Panel Id', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IPA Id', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept Existing Pat', field: 'ACCEPT_EXISTING_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'PCP Flag', field: 'PCP_FLAG', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept New Pat', field: 'ACCEPT_NEW_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'National Provider Id', field: 'NATIONAL_PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Taxonomy Code', field: 'TAXONOMY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Vendor IRS Tax ID', field: 'IRS_TAX_ID', width: 140, headerClass: 'font-weight-bold'}

    // TODO need to do all columns mappings
  ];

  public static PROVIDER_MASTER_ALL2 = [
    {headerName: 'PIMS ID', field: 'USER_DEFINED_6', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Master Speciality Type', field: 'SPECIALTY_TYPE', width: 300, headerClass: 'font-weight-bold'},
    {headerName: 'Last Name', field: 'LAST_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'First Name', field: 'FIRST_NAME', width: 150, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Contract Speciality Type', field: 'PROVIDER_CONTRACT_SPECIALTY_TYPE', width: 100, headerClass: 'font-weight-bold'},
    {headerName: 'Country', field: 'COUNTRY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 1', field: 'ADDRESS_LINE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 2', field: 'ADDRESS_LINE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'City', field: 'CITY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'State/Province', field: 'STATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Zip/Postal Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Effective Date', field: 'EFFECTIVE_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Date', field: 'TERM_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Id', field: 'SEQ_PROV_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Type', field: 'PROVIDER_TYPE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Short Name', field: 'SHORT_NAME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Middle Initial', field: 'MIDDLE_INITIAL', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Name 2', field: 'NAME_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Provider Category', field: 'PROVIDER_CATEGORY', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Prov Xref Id', field: 'SEQ_PROV_XREF_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id1 ', field: 'USER_ID1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id2 ', field: 'USER_ID2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Id3 ', field: 'USER_ID3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Date Of Birth ', field: 'DATE_OF_BIRTH', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Non Specific Prov ', field: 'NON_SPECIFIC_PROV', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Seq Vend Id', field: 'SEQ_VEND_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 1', field: 'LANGUAGE_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 2', field: 'LANGUAGE_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Language 3', field: 'LANGUAGE_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 1', field: 'USER_DEFINED_1', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 2', field: 'USER_DEFINED_2', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 3', field: 'USER_DEFINED_3', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 4', field: 'USER_DEFINED_4', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 5', field: 'USER_DEFINED_5', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined 6', field: 'USER_DEFINED_6', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'User Defined Date', field: 'USER_DEFINED_DATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Security Code', field: 'SECURITY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Datetime', field: 'INSERT_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert User', field: 'INSERT_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Insert Process', field: 'INSERT_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Datetime', field: 'UPDATE_DATETIME', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update User', field: 'UPDATE_USER', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Update Process', field: 'UPDATE_PROCESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Line of Business', field: 'LINE_OF_BUSINESS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Panel Id', field: 'PANEL_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IPA Id', field: 'IPA_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept Existing Pat', field: 'ACCEPT_EXISTING_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'PCP Flag', field: 'PCP_FLAG', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Accept New Pat', field: 'ACCEPT_NEW_PATIENTS', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'National Provider Id', field: 'NATIONAL_PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Taxonomy Code', field: 'TAXONOMY_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Term Reason', field: 'TERM_REASON', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'IRS Tax ID', field: 'IRS_TAX_ID', width: 140, headerClass: 'font-weight-bold'}
    // TODO need to do all columns mappings

  ];

  public static VENDORFIRST_PROVIDER = [
    {headerName: 'Provider ID', field: 'PROVIDER_ID', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Short Name', field: 'SHORT_NAME', width: 240, headerClass: 'font-weight-bold'},
    {headerName: 'Last Name', field: 'LAST_NAME', width: 400, headerClass: 'font-weight-bold'},
    {headerName: 'First Name', field: 'FIRST_NAME', width: 240, headerClass: 'font-weight-bold'},
    {headerName: 'Name 2', field: 'NAME_2', width: 240, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 1', field: 'ADDRESS_LINE_1', width: 400, headerClass: 'font-weight-bold'},
    {headerName: 'Address Line 2', field: 'ADDRESS_LINE_2', width: 400, headerClass: 'font-weight-bold'},
    {headerName: 'City', field: 'CITY', width: 240, headerClass: 'font-weight-bold'},
    {headerName: 'State', field: 'STATE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'Zip Code', field: 'ZIP_CODE', width: 140, headerClass: 'font-weight-bold'},
    {headerName: 'County', field: 'COUNTY', width: 140, headerClass: 'font-weight-bold'}
  ]

}
