export class TradingPartnerMasterLookup {
  public static TRADING_PARTNER_MASTER_DEFAULT = [
    {
      headerName: "Trading Partner ID",
      field: "tradingPartnerId",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Trading Partner Name",
      field: "tradingPartnerName",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Trading Partner Type",
      field: "tradingPartnerType",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Address Line 1",
      field: "addressLine1",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Address Line 2",
      field: "addressLine2",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "City",
      field: "city",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "State",
      field: "state",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Zipcode",
      field: "zipcode",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Country",
      field: "country",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Contact Name",
      field: "contactName",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Phone Number",
      field: "phoneNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Fax Number",
      field: "faxNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Email",
      field: "email",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "City",
      field: "ediAccessNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 1",
      field: "userDefined1",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 2",
      field: "userDefined2",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 3",
      field: "userDefined3",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 4",
      field: "userDefined4",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 5",
      field: "userDefined5",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 6",
      field: "userDefined6",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 7",
      field: "userDefined7",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Comments",
      field: "comments",
      width: 140,
      headerClass: "font-weight-bold",
    },
  ];

  public static TRADING_PARTNER_MASTER_ALL = [
    {
      headerName: "Trading Partner ID",
      field: "tradingPartnerId",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Trading Partner Name",
      field: "tradingPartnerName",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Address Line 1",
      field: "addressLine1",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Address Line 2",
      field: "addressLine2",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "City",
      field: "ediAccessNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "State",
      field: "state",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Zipcode",
      field: "zipcode",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Country",
      field: "country",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Contact Name",
      field: "contactName",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Phone Number",
      field: "phoneNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Fax Number",
      field: "faxNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Email",
      field: "email",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "EDI Access Number",
      field: "ediAccessNumber",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 1",
      field: "userDefined1",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 2",
      field: "userDefined2",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 3",
      field: "userDefined3",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 4",
      field: "userDefined4",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 5",
      field: "userDefined5",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 6",
      field: "userDefined6",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "User Defined 7",
      field: "userDefined7",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Comments",
      field: "comments",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Security Code",
      field: "securityCode",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert DateTime",
      field: "InsertDateTime",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert User",
      field: "insertUser",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Insert Process",
      field: "insertProcess",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update DateTime",
      field: "updateDateTime",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update User",
      field: "updateUser",
      width: 140,
      headerClass: "font-weight-bold",
    },
    {
      headerName: "Update Process",
      field: "updateProcess",
      width: 140,
      headerClass: "font-weight-bold",
    },
  ];
}
