/* Copyright (c) 2020 . All Rights Reserved. */

export class MemberEligHistory {
  riderCode20: string;
  riderCode19: string;
  riderCode18: string;
  riderCode17: string;
  riderCode16: string;
  riderCode15: string;
  riderCode14: string;
  riderCode13: string;
  riderCode12: string;
  riderCode11: string;
  riderCode10: string;
  riderCode9: string;
  mcarePartABTermDate: string;
  csIndicator: string;
  facSeqProvId: number;
  pbp: string;
  geocode: string;
  pbpEffectiveDate: string;
  mcUserDate2: string;
  mcUserDate1: string;
  mcUserDefined2: string;
  mcUserDefined1: string;
  pbpAcknowledgeIndicator: string;
  medRiskUserDate2: string;
  medRiskUserDate1: string;
  medRiskUserDefined2: string;
  medRiskUserDefined1: string;
  facMmCertification: string;
  facDischargeDate: string;
  facAdmissionDate: string;
  facPhoneNumber: string;
  facCountry: string;
  facZipCode: string;
  facCounty: string;
  facState: string;
  facCity: string;
  facAddressLine2: string;
  facAddressLine1: string;
  facName: string;
  dateOfDeath: string;
  medicarePartBEnrollDate: string;
  medicarePartAEffectDate: string;
  entMcarePipdcgFactor: number;
  entMcareWelfareFlg: string;
  entMcarePartBFlg: string;
  entMcarePartAFlg: string;
  seqSiteAddressId: number;
  siteCode: string;
  pcpChangeReason: string;
  privacyOn: string;
  pcpaaOccurred: string;
  rateType: string;
  userDefined3: string;
  userDefined2: string;
  comments: string;
  mcareRiskRefusedDate: string;
  mcareRiskDeletionDate: string;
  mcareRiskAccretionDate: string;
  seqEnrollmentRule: number;
  benefitStartDate: string;
  useEftFlg: string;
  subscLocation: string;
  subscDept: string;
  paidThruDate: any;
  billedThruDate: any;
  billEffectiveFromDate: string;
  pecWaived: string;
  reasonCode: string;
  pecEndDate: string;
  salary: number;
  userDefined1: string;
  updateProcess: string;
  updateUser: string;
  updateDatetime: string;
  insertProcess: string;
  insertUser: string;
  insertDatetime: string;
  securityCode: string;
  seqProv2Id: number;
  panelId: string;
  ipaId: string;
  seqProvId: number;
  premOverrideCode: string;
  premOverrideAmt: number;
  premOverrideStep: number;
  eligStatus: string;
  hireDate: string;
  otherStatusFlag: string;
  emirateCode: string;
  emirateArch: string;
  medicareStatusFlg: string;
  riderCode8: string;
  riderCode7: string;
  riderCode6: string;
  riderCode5: string;
  riderCode4: string;
  riderCode3: string;
  riderCode2: string;
  riderCode1: string;
  lineOfBusiness: string;
  planCode: string;
  seqGroupId: number;
  relationshipCode: string;
  termReason: string;
  termDate: string;
  effectiveDate: string;
  personNumber: string;
  subscriberId: string;
  seqSubsId: number;
  groupId: any;
  groupShortName: string;
  benefitPackageId: string;
  statecd:string;
  countycd:any;
  medicaid:string;
  updateDatetimeDisplay: string;
  insertDatetimeDisplay: string
  memberEligHistoryPrimaryKey: {
    seqMembId: number;
    seqEligHist?: number;
  };
  seqEligHist: number;
    shortName: string;
}


export class MemberEligHistoryCustom{
  Subscriber_id: string
     Person_number: string
     Last_name: string
     First_name: string
     Effective_date: string
     Term_date: string
     Elig_status: string
     Relationship_code: string
     Seq_group_id: string
     Group_id: string
     Short_name: string
     Plan_code: string
     Benefit_package_id: string
				 Short_description: string
         RiderCode1: string
}
