/* Copyright (c) 2020 . All Rights Reserved. */

import { ProvContract } from "./prov-contract.model";
import { ProvSpecialty } from "./prov-specialty.model";
import {VendorMaster} from "./vendor-master.model";
import {VendorAddress} from "./vendor-address.model";

export class ProvMaster {
  seqProvId: number;
  providerId: string;
  shortName: string;
  outOfNetStatus: string;
  participationFlag: string;
  lastName: string;
  firstName: string;
  middleInitial: string;
  providerCategory: string;
  seqProvXrefId: number;
  userId1: string;
  userId2: string;
  userId3: string;
  providerType: string;
  dateOfBirth: string;
  nonSpecificProv: string;
  ipaId: string;
  seqVendId: number;
  language1: string;
  language2: string;
  language3: string;
  userDefined1: string;
  userDefined2: string;
  userDefined3: string;
  userDefined4: string;
  userDefined5: string;
  userDefinedDate: string;
  securityCode: string;
  insertDatetime: Date;
  insertUser: string;
  insertProcess: string;
  updateDatetime: Date;
  updateUser: string;
  updateProcess: string;
  license: string;
  salutation: string;
  journalFlag: string;
  authClass: string;
  seqVendAddress: number;
  seqCapVendAddress: number;
  caseMgmtSendTms: Date;
  userDefined6: string;
  userDefined7: string;
  userDefined8: string;
  userDefined9: string;
  userDefined10: string;
  userDefined11: string;
  userDefined12: string;
  userDefined13: string;
  userDefined14: string;
  userDefined15: string;
  userDefined16: string;
  userDefinedDate2: string;
  userDefinedDate3: string;
  nationalProviderId: string;
  maxEnrollLmt: number;
  accessProgramEligible: string;
  defaultVendorAddr: string;
  defaultVendorId: string;


  specialtyType:string;
  provSpecialty:ProvSpecialty;
  provContract: ProvContract;
  contractPanelId:string;
  seqProvContract:number;
  effectiveDate: Date;
  termDate: Date;
  count:number=0;
  vendorMaster: VendorMaster;
  vendorAddress: VendorAddress;
}
